[project]
name = "agent"
version = "0.1.0"
description = ""
authors = [
    {name = "Serey Roth",email = "rserey34@gmail.com"}
]
requires-python = ">=3.13,<4.0"
dependencies = [
    "chromadb (>=1.5.9,<2.0.0)",
    "llama-index-core (>=0.14.23,<0.15.0)",
    "llama-index-llms-anthropic (>=0.11.10,<0.12.0)",
    "python-dotenv (>=1.2.2,<2.0.0)",
    "python-weather (>=2.2.3,<3.0.0)",
    "llama-index-readers-file (>=0.6.0,<0.7.0)",
    "arxiv (>=4.0.1,<5.0.0)",
    "llama-index-embeddings-huggingface (>=0.7.0,<0.8.0)",
    "llama-index-vector-stores-chroma (>=0.5.5,<0.6.0)"
]

[tool.poetry]
packages = [{include = "*", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
